index:
    path: /
    controller: App\Controller\BaseController::index

text:
    path: /txt
    controller: App\Controller\BaseController::textGenerator

balls:
    path: /balls
    controller: App\Controller\BaseController::balls

dress-up:
    path: /dress-up
    controller: App\Controller\BaseController::dressUpGame